# Generated by Django 5.2 on 2025-05-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_doctor_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='meds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfr', models.TextField(blank=True, null=True)),
                ('afr', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
