# Generated by Django 5.2 on 2025-05-08 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_meds_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pvitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField(blank=True, null=True)),
                ('sugar', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('body_temp', models.IntegerField(blank=True, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
