# Generated by Django 5.2 on 2025-05-08 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvitals',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
