# Generated by Django 5.2 on 2025-05-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pvitals_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meds',
            name='user',
        ),
        migrations.AddField(
            model_name='meds',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.rfid'),
        ),
    ]
